feat: implement loading indicator
EOX-A/EOxElements pull request #1200
Opened 2024-08-07 07:38 UTC by spectrachrome

## Implemented changes

Implements a loading indicator for the EOxGeoSearch element.
Note, how can we make this consistent with the OL loader used in the EOxMap?

## Screenshots/Videos

Coming soon...

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added a test related to this feature/fix
- [ ] For new features: I have created a story showcasing this new feature
- [ ] All checks have passed
- [ ] The PR title [follows conventional commit style and reflects the type of change (major/minor/patch, breaking)](https://github.com/googleapis/release-please?tab=readme-ov-file#how-should-i-write-my-commits)
- [ ] The PR title describes the change within this element (each merged PR equals one entry in the element's changelog!)

2024-08-07 11:14 UTC, silvester-pari requested changes
Thank you, yes we could think of centralizing the default spinner to a shareable package.

But the bigger concern currently is that the spinner is hardcoded in your proposed change, so there is no way to replace/style it. Usually, we either provide CSS variables or dedicated properties for customizing such things.

Also, it seems you didn't use the default spinner from eox-map, maybe you used the one from an example story? I think the default one is much thinner and not colored red.

2024-08-07 11:22 UTC, spectrachrome commented
Yes, I used the full screen variant of Robert's loading indicator:
https://github.com/EOX-A/EOxElements/pull/1173/files#diff-d6260890d082a80ce9b6cae725a4300e6e6f74e3aa3b27090b11aa189359e83cR360-R362

Thank you for the review, I will try to use the normal map loader and use either CSS variables or something like a custom `loaderSvg` attribute to make it customizable.

2024-08-07 12:31 UTC, spectrachrome commented
Default spinner is now used, an alternative SVG spinner can be provided in the `loaderSvg` attribute and a new Custom Loader story has been added.

2024-08-08 11:54 UTC, silvester-pari approved these changes

2024-08-08 11:54 UTC, merged