Allow setting step in range filter
EOX-A/EOxElements pull request #1202
Opened 2024-08-07 08:09 UTC by viktoraronfarkas

## Implemented changes

## Screenshots/Videos

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added a test related to this feature/fix
- [ ] For new features: I have created a story showcasing this new feature
- [ ] All checks have passed
- [ ] The PR title [follows conventional commit style and reflects the type of change (major/minor/patch, breaking)](https://github.com/googleapis/release-please?tab=readme-ov-file#how-should-i-write-my-commits)
- [ ] The PR title describes the change within this element (each merged PR equals one entry in the element's changelog!)

2024-08-13 15:00 UTC, santilland approved these changes
Examples looks good, all tests pass. It is good to have the stepsize option, so from my side, cool! Thanks for the implementation!

2024-08-14 11:59 UTC, srijitcoder approved these changes

2024-08-14 11:59 UTC, srijitcoder approved these changes
Looks good! 🎉

2024-08-19 05:59 UTC, silvester-pari requested changes
Thanks for this addition, however, the stories don't make sense at this moment as there is no "range" property in the test items, so the user trying out the story doesn't see anything happening. Could you add a demo property to the `/test/testItems.json`?

2024-08-19 14:57 UTC, silvester-pari approved these changes

2024-08-19 14:58 UTC, merged