Feat: Themeing using CSS variable and property
EOX-A/EOxElements pull request #616
Opened 2024-02-05 09:32 UTC by srijitcoder

## Implemented changes

## Screenshots/Videos

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added a test related to this feature/fix
- [ ] For new features: I have created a story showcasing this new feature
- [ ] All checks have passed
- [ ] The PR title [follows conventional commit style and reflects the type of change (major/minor/patch, breaking)](https://github.com/googleapis/release-please?tab=readme-ov-file#how-should-i-write-my-commits)
- [ ] The PR title describes the change within this element (each merged PR equals one entry in the element's changelog!)

2024-02-05 10:40 UTC, StefanBrand commented
I noticed that we tend to use negative terms to name our props, like `disablePlay` in https://github.com/EOX-A/EOxElements/pull/615 or `noShadow`. This often leads to double negations, which are to be avoided <sup>[Citation needed]</sup>. I propose to replace the name of the `noShadow` prop by something positive like `useShadowRoot`.

2024-02-05 10:50 UTC, silvester-pari commented
> I noticed that we tend to use negative terms to name our props, like `disablePlay` in #615 or `noShadow`. This often leads to double negations, which are to be avoided [Citation needed]. I propose to replace the name of the `noShadow` prop by something positive like `useShadowRoot`.

Good idea, we can do e.g. `useShadowRoot` property / `use-shadow-root` attribute, or just `useShadow` or even `shadow` :
- undefined --> true
- true --> true
- false --> false

2024-02-12 14:08 UTC, silvester-pari requested changes
Thank you for this setup, which looks promising if we manage to iron some things out (see comments). One more general thing:

## Variable naming
We now use an internal variable name prefixed with `--eox-` and an external without. This could lead to mixups with other CSS variables used in the parent app with a similar name. I guess using the prefixed name is the one we should expose, like e.g. in the story it should look like 
```
<style>
      html,
      :host,
      :root {
        --eox-secondary-color: #ffa55c;
        --eox-bg-hover-transparency: 20%;
        --eox-color: #ffa55c;
        --eox-body-font-family: "Comic Sans MS", cursive;
      }
    </style>
```

2024-02-12 14:08 UTC, silvester-pari commented on elements/drawtools/src/style.js
Not sure why this was deleted? This was the "minimum style" required for the unstyled version to work. I agree that in the drawtools case this is very minimal, but in other element's cases this contains some basic styling that needs to be there, otherwise the element doesn't work. We can arrange this differently and name the files differently, but the order should be

```
// unstyled
+ required style // minimum style to make the element work
// styled
+ main EOX styling including CSS vars
+ element specific style
```

2024-02-12 15:48 UTC, srijitcoder commented on elements/drawtools/stories/css-variable-override.js
> + * Component demonstrating css variable override when
Done ✅

2024-02-12 15:48 UTC, srijitcoder commented on elements/drawtools/stories/css-variable-override.js
> +    <!-- Initialize eox-drawtools for the eox-map with ID "list" -->
Done ✅

2024-02-12 15:48 UTC, srijitcoder commented on elements/drawtools/stories/index.js
> +export { default as CSSVariableOverrideStory } from "./css-variable-override"; // Story demonstrating css override in `noShadow` property
Done ✅

2024-02-12 15:48 UTC, srijitcoder commented on elements/drawtools/stories/drawtools.stories.js
> + * By passing `noShadow=true` we can override css variable directly using styles.
Done ✅

2024-02-12 15:48 UTC, srijitcoder commented on elements/drawtools/stories/css-variable-override.js
> +      .noShadow=${false}
Done ✅

2024-02-12 16:09 UTC, silvester-pari approved these changes

2024-02-12 16:10 UTC, merged