feat: removing summary title for single item groups, adding hierarchy positioning
EOX-A/EOxElements pull request #792
Opened 2024-03-27 10:20 UTC by santilland

## Implemented changes

When using aggregate results and a summary section only contains one entry this removes the summary section and shows directly the item. It also adds a left margin for entries within summary groups to better differentiate hierarchy.

## Screenshots/Videos

![image](https://github.com/EOX-A/EOxElements/assets/4036819/a4484c33-459d-45c5-97c7-ba3b59cfc4f2)

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added a test related to this feature/fix
- [ ] For new features: I have created a story showcasing this new feature
- [ ] All checks have passed
- [x] The PR title [follows conventional commit style and reflects the type of change (major/minor/patch, breaking)](https://github.com/googleapis/release-please?tab=readme-ov-file#how-should-i-write-my-commits)
- [x] The PR title describes the change within this element (each merged PR equals one entry in the element's changelog!)

2024-03-27 10:35 UTC, santilland commented
maybe.... we want to have this as a configuration option?

2024-04-02 07:30 UTC, silvester-pari requested changes
Thanks @santilland! I'd say this would be nice as a config option, as it feels kinda strange as a default rendering imo.

2024-04-02 08:10 UTC, santilland commented
I added it as option `autoSpreadSingle`

2024-04-02 14:06 UTC, silvester-pari approved these changes

2024-04-02 14:46 UTC, merged